// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_preferences.proto

// Protobuf Java Version: 3.25.0
package com.data.user.data.datastore;

/**
 * Protobuf type {@code UserPreferencesDataStore}
 */
public  final class UserPreferencesDataStore extends
    com.google.protobuf.GeneratedMessageLite<
        UserPreferencesDataStore, UserPreferencesDataStore.Builder> implements
    // @@protoc_insertion_point(message_implements:UserPreferencesDataStore)
    UserPreferencesDataStoreOrBuilder {
  private UserPreferencesDataStore() {
    name_ = "";
    email_ = "";
    accessToken_ = "";
    refreshToken_ = "";
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @Override
  public String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      String value) {
    Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private String email_;
  /**
   * <code>string email = 2;</code>
   * @return The email.
   */
  @Override
  public String getEmail() {
    return email_;
  }
  /**
   * <code>string email = 2;</code>
   * @return The bytes for email.
   */
  @Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(email_);
  }
  /**
   * <code>string email = 2;</code>
   * @param value The email to set.
   */
  private void setEmail(
      String value) {
    Class<?> valueClass = value.getClass();
  
    email_ = value;
  }
  /**
   * <code>string email = 2;</code>
   */
  private void clearEmail() {

    email_ = getDefaultInstance().getEmail();
  }
  /**
   * <code>string email = 2;</code>
   * @param value The bytes for email to set.
   */
  private void setEmailBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    email_ = value.toStringUtf8();

  }

  public static final int ACCESS_TOKEN_FIELD_NUMBER = 3;
  private String accessToken_;
  /**
   * <code>string access_token = 3;</code>
   * @return The accessToken.
   */
  @Override
  public String getAccessToken() {
    return accessToken_;
  }
  /**
   * <code>string access_token = 3;</code>
   * @return The bytes for accessToken.
   */
  @Override
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(accessToken_);
  }
  /**
   * <code>string access_token = 3;</code>
   * @param value The accessToken to set.
   */
  private void setAccessToken(
      String value) {
    Class<?> valueClass = value.getClass();
  
    accessToken_ = value;
  }
  /**
   * <code>string access_token = 3;</code>
   */
  private void clearAccessToken() {

    accessToken_ = getDefaultInstance().getAccessToken();
  }
  /**
   * <code>string access_token = 3;</code>
   * @param value The bytes for accessToken to set.
   */
  private void setAccessTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    accessToken_ = value.toStringUtf8();

  }

  public static final int REFRESH_TOKEN_FIELD_NUMBER = 4;
  private String refreshToken_;
  /**
   * <code>string refresh_token = 4;</code>
   * @return The refreshToken.
   */
  @Override
  public String getRefreshToken() {
    return refreshToken_;
  }
  /**
   * <code>string refresh_token = 4;</code>
   * @return The bytes for refreshToken.
   */
  @Override
  public com.google.protobuf.ByteString
      getRefreshTokenBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(refreshToken_);
  }
  /**
   * <code>string refresh_token = 4;</code>
   * @param value The refreshToken to set.
   */
  private void setRefreshToken(
      String value) {
    Class<?> valueClass = value.getClass();
  
    refreshToken_ = value;
  }
  /**
   * <code>string refresh_token = 4;</code>
   */
  private void clearRefreshToken() {

    refreshToken_ = getDefaultInstance().getRefreshToken();
  }
  /**
   * <code>string refresh_token = 4;</code>
   * @param value The bytes for refreshToken to set.
   */
  private void setRefreshTokenBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    refreshToken_ = value.toStringUtf8();

  }

  public static UserPreferencesDataStore parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static UserPreferencesDataStore parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static UserPreferencesDataStore parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static UserPreferencesDataStore parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static UserPreferencesDataStore parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static UserPreferencesDataStore parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static UserPreferencesDataStore parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static UserPreferencesDataStore parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static UserPreferencesDataStore parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static UserPreferencesDataStore parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static UserPreferencesDataStore parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static UserPreferencesDataStore parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(UserPreferencesDataStore prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code UserPreferencesDataStore}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        UserPreferencesDataStore, Builder> implements
      // @@protoc_insertion_point(builder_implements:UserPreferencesDataStore)
      com.data.user.data.datastore.UserPreferencesDataStoreOrBuilder {
    // Construct using com.eventhngs.user.UserPreferencesDataStore.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string email = 2;</code>
     * @return The email.
     */
    @Override
    public String getEmail() {
      return instance.getEmail();
    }
    /**
     * <code>string email = 2;</code>
     * @return The bytes for email.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return instance.getEmailBytes();
    }
    /**
     * <code>string email = 2;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        String value) {
      copyOnWrite();
      instance.setEmail(value);
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      copyOnWrite();
      instance.clearEmail();
      return this;
    }
    /**
     * <code>string email = 2;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEmailBytes(value);
      return this;
    }

    /**
     * <code>string access_token = 3;</code>
     * @return The accessToken.
     */
    @Override
    public String getAccessToken() {
      return instance.getAccessToken();
    }
    /**
     * <code>string access_token = 3;</code>
     * @return The bytes for accessToken.
     */
    @Override
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      return instance.getAccessTokenBytes();
    }
    /**
     * <code>string access_token = 3;</code>
     * @param value The accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessToken(
        String value) {
      copyOnWrite();
      instance.setAccessToken(value);
      return this;
    }
    /**
     * <code>string access_token = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessToken() {
      copyOnWrite();
      instance.clearAccessToken();
      return this;
    }
    /**
     * <code>string access_token = 3;</code>
     * @param value The bytes for accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAccessTokenBytes(value);
      return this;
    }

    /**
     * <code>string refresh_token = 4;</code>
     * @return The refreshToken.
     */
    @Override
    public String getRefreshToken() {
      return instance.getRefreshToken();
    }
    /**
     * <code>string refresh_token = 4;</code>
     * @return The bytes for refreshToken.
     */
    @Override
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      return instance.getRefreshTokenBytes();
    }
    /**
     * <code>string refresh_token = 4;</code>
     * @param value The refreshToken to set.
     * @return This builder for chaining.
     */
    public Builder setRefreshToken(
        String value) {
      copyOnWrite();
      instance.setRefreshToken(value);
      return this;
    }
    /**
     * <code>string refresh_token = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRefreshToken() {
      copyOnWrite();
      instance.clearRefreshToken();
      return this;
    }
    /**
     * <code>string refresh_token = 4;</code>
     * @param value The bytes for refreshToken to set.
     * @return This builder for chaining.
     */
    public Builder setRefreshTokenBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRefreshTokenBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserPreferencesDataStore)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new UserPreferencesDataStore();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "name_",
            "email_",
            "accessToken_",
            "refreshToken_",
          };
          String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<UserPreferencesDataStore> parser = PARSER;
        if (parser == null) {
          synchronized (UserPreferencesDataStore.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<UserPreferencesDataStore>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:UserPreferencesDataStore)
  private static final UserPreferencesDataStore DEFAULT_INSTANCE;
  static {
    UserPreferencesDataStore defaultInstance = new UserPreferencesDataStore();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserPreferencesDataStore.class, defaultInstance);
  }

  public static UserPreferencesDataStore getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserPreferencesDataStore> PARSER;

  public static com.google.protobuf.Parser<UserPreferencesDataStore> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

