// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_preferences.proto

// Protobuf Java Version: 3.25.0
package com.data.user.data.datastore;

public final class UserPreferences {
  private UserPreferences() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
